### PR TITLE
Fix notation

### PR DESCRIPTION
**Pull request by duncanhobbs**
This PR is a first pass at addressing issue #39 and adjusts the notation and docstrings in the files containing the equations to match the Hashimoto textbook.

Let me know if I need to add anything else to this PR.

### CODE REVIEW

**Comment by duncanhobbs** [comment]
I have added some commits to fix the testing errors. Apologies for being slow to fix this.

Let me know if you would like me to add anything else to this PR.

@jdebacker

**Comment by jdebacker** [comment]
@duncanhobbs All these changes LGTM.  Just let me know when you are finished and I'll merge this PR.  Thanks!

**Comment by duncanhobbs** [comment]
@jdebacker I finished looking over the files and I think the notation is consistent with Hashimoto.

**Comment by jdebacker** [comment]
Excellent.  Thanks for another contribution @duncanhobbs

**Pull request merged**
