### PR TITLE
Add separate function for disposable income to  household.py and simple CGE.py

### PR DESCRIPTION
**Pull request by duncanhobbs**
This PR adds a separate function to compute individual incomes raised in \#22 to `household.py` and `simple CGE.py`

### CODE REVIEW

**Comment by jdebacker** [comment]
@duncanhobbs This looks good - thanks for another contribution.  Before I merge (and since we don't have much in the way of testing yet), can you confirm that you can successfully run the model on this branch?

**Comment by duncanhobbs** [comment]
I am getting an error when I ran the model:

I am using windows 7 and running from inside the `cge_env` environment.

```
(cge_env) C:\Users\duncan.hobbs\Github\PSL\CGE\open_cge> python simpleCGE.py

C:\Users\duncan.hobbs\Github\PSL\CGE\open_cge\aggregates.py:95: RuntimeWarning:
invalid value encountered in double_scalars
  Kk = (pf['CAP'] * Ff['CAP']) / (R * ((lam * pq).sum()))
Distance at iteration  1  is  0.0
Model solved, Q =  AGR   NaN
OIL   NaN
IND   NaN
SER   NaN
dtype: float64

```

I switched to the master branch and tried to run the model again and I got the same error. I am not quite sure where the invalid value is coming from.

**Comment by jdebacker** [comment]
@duncanhobbs Thanks for testing that.  I'll try to run off your branch on my machine.  I've been working with @rkasher and he's getting an error similar to you on a Windows machine.  It only cropped up recently, so it may be related to some changes to the dependency packages.

**Comment by duncanhobbs** [comment]
I looked at the error and the issue may be that the denominator of the Kk equation `(R * ((lam * pq).sum()))` is set to 0, and numpy throws an error because it can't divide by 0.

I checked the components of the denominator, and I think that R is being set to 0.0 for some reason.

From [simpleCGE.py](https://github.com/PSLmodels/CGE/blob/fbcb028a84b1484b656a11417b304b3486a3ca6b/open_cge/simpleCGE.py#L105)

```
# Load data and parameters classes
d = calibrate.model_data(sam, h, u, ind)
p = calibrate.parameters(d, ind)

XXg = d.XXg0
R = d.R0

print(R)
```
When I printed R to the console it gave a value of 0.0.

@jdebacker @rkasher

**Comment by jdebacker** [comment]
I had not issue running this branch.  Here's my output:

```
(base) A02655JDEBACKER:downloads jason.debacker$ cd CGE-sep-disposable-income
(base) A02655JDEBACKER:CGE-sep-disposable-income jason.debacker$ ls
README.md	open_IO		read-the-docs
environment.yml	open_cge	setup.py
(base) A02655JDEBACKER:CGE-sep-disposable-income jason.debacker$ source activate cge_env
(cge_env) A02655JDEBACKER:CGE-sep-disposable-income jason.debacker$ pip install -e .
Obtaining file:///Users/jason.debacker/Downloads/CGE-sep-disposable-income
Installing collected packages: open-cge
  Found existing installation: open-cge 0.1.0
    Uninstalling open-cge-0.1.0:
      Successfully uninstalled open-cge-0.1.0
  Running setup.py develop for open-cge
Successfully installed open-cge
(cge_env) A02655JDEBACKER:CGE-sep-disposable-income jason.debacker$ ls
README.md		open_cge		setup.py
environment.yml		open_cge.egg-info
open_IO			read-the-docs
(cge_env) A02655JDEBACKER:CGE-sep-disposable-income jason.debacker$ cd open_cge
(cge_env) A02655JDEBACKER:open_cge jason.debacker$ ls
CGE_equations.py	equations.py		simpleCGE.py
SAM.xlsx		firms.py		tests
aggregates.py		government.py
calibrate.py		household.py
(cge_env) A02655JDEBACKER:open_cge jason.debacker$ python simpleCGE.py
Distance at iteration  1  is  4.121147867408581e-12
Model solved, Q =  AGR     116.0
OIL     149.0
IND    1432.0
SER    1803.0
dtype: float64
```

**Comment by duncanhobbs** [comment]
This might be a Windows problem.

I looked at the components of `R0` to see why it is showing up as 0 when I run the file.

When I `print(Ff0)`

```
(cge_env) C:\Users\duncan.hobbs\Github\PSL\CGE\open_cge> python simpleCGE.py
LAB     0.0
CAP     0.0
LAND    0.0
NTR     0.0
dtype: float64
```


When I `print(F0)`

```
(cge_env) C:\Users\duncan.hobbs\Github\PSL\CGE\open_cge> python simpleCGE.py
      AGR  OIL  IND  SER
LAB   NaN  NaN  NaN  NaN
CAP   NaN  NaN  NaN  NaN
LAND  NaN  NaN  NaN  NaN
NTR   NaN  NaN  NaN  NaN
```

I am not sure why this part of SAM.xlsx is imported as NAN when these things should be numbers

**Comment by jdebacker** [comment]
@duncanhobbs Good find.  Sounds like the place to check is the `sam = pd.read_excel(sam_path)` in `simpleCGE.py` and maybe what's going on with the loading of these data into different DataFrames in the `model_data()` class in `calibrate.py`.   Could there be an encoding issue reading the Excel file into Pandas in a Windows OS?

**Comment by duncanhobbs** [comment]
@jdebacker 

I specified `sam = pd.read_excel(sam_path, index_col=0, header=0)` to make sure the first row and column of SAM.xlsx were not counted as data, and I think this solves the issue.

I get the following output:

```
(cge_env) C:\Users\duncan.hobbs\Github\PSL\CGE\open_cge> python simpleCGE.py
Distance at iteration  1  is  4.121147867408581e-12
Model solved, Q =  AGR     116.0
OIL     149.0
IND    1432.0
SER    1803.0
dtype: float64
```

This matches the output that you generated above.

**Comment by jdebacker** [comment]
Excellent!  Is this PR ready to be merged then?

**Comment by duncanhobbs** [comment]
Yes. Everything checks out.

I am also working on writing a test for the new function. Does it make sense to submit that in a separate PR?

**Comment by jdebacker** [comment]
> I am also working on writing a test for the new function.

Great!   Put that in this PR.  It's good form to add a test for any new functions contributed.  Thanks!  Ping me when you think this is ready to go.

**Comment by duncanhobbs** [comment]
@jdebacker 

I added test functions for `eqI():` and `eqXp():` to `test_household.py`. Sorry the commit history is a little messy. 

Here is the test output:

(```
cge_env) C:\Users\duncan.hobbs\Github\PSL\CGE\open_cge\tests> pytest test_house
hold.py
C:\Users\duncan.hobbs\AppData\Local\Continuum\anaconda3\envs\cge_env\lib\site-pa
ckages\pep8.py:110: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
============================= test session starts =============================
platform win32 -- Python 3.7.3, pytest-4.4.0, py-1.8.0, pluggy-0.9.0
rootdir: C:\Users\duncan.hobbs\Github\PSL\CGE
plugins: xdist-1.26.1, pep8-1.0.6, forked-1.0.2
collected 3 items

test_household.py ...                                                    [100%] 
```

**Comment by jdebacker** [comment]
Thanks for another contribution @duncanhobbs!

**Pull request merged**
