### PR TITLE
Input Output multiplier model and pq change in CGE

### PR DESCRIPTION
**Pull request by DPrihardini**
Simple example of an input output price multiplier model

### CODE REVIEW

**Comment by DPrihardini** [comment]
Changed the pq equation in CGE model from a market clearing condition to directly calculating pq using CES price aggregator formula. Model now runs on my PC. Will need to do a few more checks to make sure that we're replicating the results from solving the model in GAMS.

**Comment by jdebacker** [comment]
@DPrihardini Thanks!  This looks good.  Sounds like you might want to do a little more with this PR - so just let me know when you are ready and I'll merge this.

**Comment by jdebacker** [comment]
@DPrihardini Just went ahead and merged this... working with @rkasher on some refactoring and testing.

**Comment by DPrihardini** [comment]
@jdebacker Thanks! Sorry, life got in the way, but I did get a bit further with the model code since I created this PL. There is still an issue with being able to replicate the results of the model coded in GAMS. Shall I create a PL for the latest version?

**Pull request merged**
